config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'gadgets#index'

  resources :gadgets
end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  belongs_to :user

  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gadget

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gadgets

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  respond_to :html
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :find_gadget, only: [:show, :edit, :update, :destroy]

  def index
    params[:mode] ||= 'cover_flow'
    @gadgets = GadgetSearch.new(current_user).perform(params[:name])
  end

  def new
    @gadget = Gadget.new
  end

  def create
    @gadget = current_user.gadgets.create(gadget_params)
    respond_with(@gadget)
  end

  def show
    respond_with(@gadget)
  end

  def edit
    respond_with(@gadget)
  end

  def update
    @gadget.update(gadget_params)
    respond_with(@gadget)
  end

  def destroy
    @gadget.destroy
    respond_with(@gadget)
  end

  private

  def find_gadget
    @gadget = current_user.gadgets.find(params[:id])
  end

  def gadget_params
    params.require(:gadget).permit(:name, pictures_attributes: [:id, :image, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    messages = ''

    flash.each do |type, message|
      if %w(notice alert).include? type
        class_type = case type
          when 'notice' then 'success'
          when 'alert' then 'warning'
        end
        messages << content_tag(:div, message, class: "alert alert-#{class_type}")
      end
    end

    messages.html_safe
  end
end

app/helpers/gadget_helper.rb
module GadgetHelper
  def list_picture_for(gadget)
    image_tag gadget.pictures.first.image.small if gadget.pictures.any?
  end

  def thumb_picture_url_for(gadget)
    gadget.pictures.first.image.thumb if gadget.pictures.any?
  end

  def cover_picture_url_for(gadget)
    gadget.pictures.first.image if gadget.pictures.any?
  end

  def classes_for_modes(mode, current_mode)
    classes = 'btn btn-default'
    classes << ' active' if current_mode == mode
    classes
  end

  def link_to_mode(mode)
    link_to mode.humanize, gadgets_path(mode: mode),
      :class => classes_for_modes(mode, params[:mode])
  end
end

app/views/application/_navigation.html.slim
nav.navbar.navbar-default role="navigation"
  .container-fluid
    .navbar-header
      = link_to 'Inspector Gadget', root_path, class: 'navbar-brand'

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          = link_to 'Gadgets', gadgets_path

      - if user_signed_in?
        ul.nav.navbar-nav.navbar-right
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown"
              = current_user.email
              b.caret
            ul.dropdown-menu
              li
                = link_to 'Logout', destroy_user_session_path, method: 'delete'

app/views/gadgets/_cover_flow_mode.html.slim
.fotorama data-nav="thumbs"
  - gadgets.each do |gadget|
    div data-thumb="#{thumb_picture_url_for(gadget)}" data-img="#{cover_picture_url_for gadget}"
      = link_to gadget.name, gadget

app/views/gadgets/_form.html.slim
.row
  .col-lg-4
    = simple_nested_form_for gadget do |f|
      = f.input :name

      = f.simple_fields_for :pictures do |fp|
        = image_tag fp.object.image.small
        = fp.input :image, as: :file
        = fp.link_to_remove 'Remove image'
        hr
      p
        = f.link_to_add 'Add new image', :pictures

      = f.button :submit

app/views/gadgets/_list_mode.html.slim
- gadgets.each do |gadget|
  .gadget
    hr
    = list_picture_for gadget
    p
      = link_to gadget.name, gadget
    p
      = link_to 'Remove', gadget, method: 'delete'

app/views/gadgets/_search.html.slim
.row
  .col-md-5
    = form_tag gadgets_path, method: 'get'  do
      = hidden_field_tag :mode, params[:mode]
      = text_field_tag :name, params[:name], class: 'form-control'
      br
      = submit_tag 'Search', class: 'btn btn-success'

app/views/gadgets/edit.html.slim
h1 = @gadget.name

= render 'form', gadget: @gadget

app/views/gadgets/index.html.slim
h1 Gadgets

= render 'search'

= link_to 'Add', new_gadget_path, class: 'btn btn-primary'
hr

.btn-group
  = link_to_mode 'list'
  = link_to_mode 'cover_flow'
hr

- if @gadgets.any?
  - if params[:mode] == 'list'
    = render 'list_mode', gadgets: @gadgets
  - elsif params[:mode] == 'cover_flow'
    = render 'cover_flow_mode', gadgets: @gadgets
- else
  p Nothing found

app/views/gadgets/new.html.slim
h1 New gadget

= render 'form', gadget: @gadget

app/views/gadgets/show.html.slim
h1 = @gadget.name.capitalize

= link_to 'Edit', edit_gadget_path(@gadget), class: 'btn btn-success'
hr

.fotorama data-nav="thumbs"
  - @gadget.pictures.each do |picture|
    a href="#{picture.image}"
      = image_tag picture.image.thumb

app/views/layouts/application.html.slim
html
  head
    title Gadgets

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

body
  .container
    = render 'navigation'
    = flash_messages

    = yield